### ISSUE TITLE
Bug List

### ISSUE THREAD

**Issue by Glubbable** [Benoist3012/Slender-Fortress-New-Versions#9]
Know Bugs:
-None

**Comment by Benoist3012** [comment]
#d18167e1dad1efed3b44987eba58f3b412e0638c

**Comment by Benoist3012** [comment]
Comit d18167e1dad1efed3b44987eba58f3b412e0638c

**Comment by Benoist3012** [comment]
fix #d18167e1dad1efed3b44987eba58f3b412e0638c

**Comment by Benoist3012** [comment]
resolved

**Comment by ScootyBootySauce** [comment]
Hi bosses like The Rake or Tryphobia (basicly all bosses with animations) are sliding

Know why this is

Yes i'm running stock configs

**Comment by ghost** [comment]
0.3.2B
Special Rounds bugs: 

-Single Player Round and Bonus Duck Special round are not working

-Double Roulette bugs: getting a second (forced), will not trigger another 2. (possible code end area)
                                   : Special Round Revolutions does not work during a double roulette (even if not forced)

**Comment by Kenzzer** [comment]
-Single Player and Bonus Duck round as disabled, until I get time to work back on, for now I'm improving the mod.

-"Double Roulette bugs: getting a second (forced), will not trigger another 2. (possible code end area)"
I don't understand, what do you mean?I will try to answer. You can't force a double roulette inside a double roulette, I blocked that because it makes no sense.

-": Special Round Revolutions does not work during a double roulette (even if not forced)"
I've also blocked that.

Global answer: those things aren't bugs.

**Comment by ghost** [comment]
Hi Benoist, Thanks for your reply.

Special Round Revolutions may still get selected in double roulette rounds (even if not forced). I am currently using your latest plugin (0.3.2C - AFK Timer fix)

And for rounds that are not fixed/not allowed, are you able to disallow forcing? Because, forcing a special round (sf2_specialround_forcetype) will still get selected, although you claimed that rounds that are not supposed to be selected will be blocked

Thanks,
Sapphire Jasper

**Comment by Kenzzer** [comment]
Hi,
Oh special round revolution doesn't work if the double roulette picks it. Alright I will take a look to it.
And for the force type well I'm using it for testing purposes, so I can test the duck/single player round.

**Comment by ghost** [comment]
Hi Benoist.

Noted with thanks. Also, to make things a bit similar to Slender, may I suggest (if you wish), when no pages/items are collected when the grace time ends, can there be an option to disable boss spawning? 

Simple pseudo:

If pages collected value = 0
{
  don't spawn boss
}
 else
{ 
spawn boss
}

Thank you!
Sapphire Jasper

**Comment by Kenzzer** [comment]
Hi,
Hmm why not, I will probably make "teleport_min_page" "teleport_max_page" cfg keys, as you know the mod is reading a cfg, so is that okay if I make them like that?

**Comment by xChillax** [comment]
I have to admit that's an exellent idea, it can even help out into the making of Adventure/Raid maps, as for example only certains "monsters" would appear per area.

**Comment by ghost** [comment]
Just gotten a small error this morning.

L 04/25/2016 - 08:43:07: [SM] Plugin encountered error 15: Array index is out of bounds
L 04/25/2016 - 08:43:07: [SM] Displaying call stack trace for plugin "sf2.smx":
L 04/25/2016 - 08:43:07: [SM]   [0]  Line 326, sf2/npc/npc_chaser.sp::NPCChaserGetState()
L 04/25/2016 - 08:43:07: [SM]   [1]  Line 1370, sf2/npc.sp::Hook_HitboxOnTakeDamage()
L 04/25/2016 - 08:48:43: [SM] Plugin encountered error 15: Array index is out of bounds
L 04/25/2016 - 08:48:43: [SM] Displaying call stack trace for plugin "sf2.smx":
L 04/25/2016 - 08:48:43: [SM]   [0]  Line 326, sf2/npc/npc_chaser.sp::NPCChaserGetState()
L 04/25/2016 - 08:48:43: [SM]   [1]  Line 1370, sf2/npc.sp::Hook_HitboxOnTakeDamage()

**Comment by ghost** [comment]
Hi.

One of the special rounds: START RUNNING (no grace period and difficulty set to Hardcore), will not work with maps with long intro such as slender_swarm_v1b.

**Comment by x3m77rus** [comment]
Good Day!

In continuing **SapphireJasper** post

L 04/29/2016 - 11:06:20: [SM] Plugin encountered error 15: Array index is out of bounds
L 04/29/2016 - 11:06:20: [SM] Displaying call stack trace for plugin "sf2/sf2.smx":
L 04/29/2016 - 11:06:20: [SM]   [0]  Line 324, sf2/npc.sp::NPCGetProfile()
L 04/29/2016 - 11:06:20: [SM]   [1]  Line 3603, sf2/client.sp::Timer_ClientResetDeathCam1()

These errors are caused by the same reason.

Also two bugs with proxies:
1) If you enable auto spawn in PvP area and will be choosen as proxy, you will spawn in PvP area as proxy with overlay, control meter and etc.
2) Sometimes proxies can't do and receive damage like if you in blue team outside of PvP area. Even on the contrary, sometimes you can do and recieve damage, but mostly can't. Doesn't matter with class you will spawn.

**Comment by ghost** [comment]
Same Reason? What do you mean? o.o?

**Comment by x3m77rus** [comment]
Yours and mines errors caused when some function tries to read or write array value with wrong index, where index is iNPCIndex variable that bigger than MAX_BOSSES or less than 0.

**Comment by Kenzzer** [comment]
Somehow git-hub close the issue, I was just trying to reference it, anyway, so it's fixed and sorry I have been busy with irl stuff for the past few days.

**Comment by ghost** [comment]
L 05/06/2016 - 23:06:46: [SM] Native "GetClientEyePosition" reported: Invalid client index 0
L 05/06/2016 - 23:06:46: [SM] Displaying call stack trace for plugin "sf2.smx":
L 05/06/2016 - 23:06:46: [SM]   [0]  Line 2313, C:\Users\Benoist\Desktop\sf2 compiler 1.7+\addons\sourcemod\scripting\sf2.sp::Command_AddSlender()

Adding a boss with Remote Console causes this. But maybe because, adding boss, requires a client and crosshair.

**Comment by x3m77rus** [comment]
[SM] Native "GetClientEyePosition" reported: Invalid client index 0 - this is an answer. Need a valid client, who looking somewhere.

**Comment by Kenzzer** [comment]
The command should be used by an admin in-game, and not via the console. Client 0 is the server for sourcemod, that's why you are getting an error.

**Comment by ghost** [comment]
Hi Benoist, I have used the latest version, 0.3.2C along with ur latest version of Navmesh.

It seems some bosses have been affected. They don't spawn.

Can I add you? I will see if I can try sought out this error.

**Comment by x3m77rus** [comment]
Hi! I know, you dont support new dev release, but just one question, SM 1.8 is a mandatory to compile? 1.7.3 compiller said:
sf2.sp(5400) : error 105: cannot find method or property Event.FireToClient

**Comment by Kenzzer** [comment]
yes, it's required, that's why we are under dev releases, sorry.

**Comment by Dalix** [comment]
L 06/02/2016 - 22:04:42: [SM] Native "GetArrayString" reported: Invalid Handle 0 (error: 4)
L 06/02/2016 - 22:04:42: [SM] Displaying call stack trace for plugin "sf2.smx":
L 06/02/2016 - 22:04:42: [SM]   [0]  Line 213, sf2/specialround.sp::Timer_SpecialRoundCycle()

**Comment by x3m77rus** [comment]
Hi! Missing SPECIALROUND_MULTIEFFECT and SPECIALROUND_DISTORTION in special rounds enum

**Comment by Dalix** [comment]
Multieffect special round bug:

L 06/08/2016 - 15:07:22: [SM] Exception reported: Client index 420 is not valid
L 06/08/2016 - 15:07:22: [SM] Blaming: sf2.smx()
L 06/08/2016 - 15:07:22: [SM] Call stack trace:
L 06/08/2016 - 15:07:22: [SM]   [0] TF2_IgnitePlayer
L 06/08/2016 - 15:07:22: [SM]   [1] Line 2690, sf2/npc/npc_chaser.sp::Timer_SlenderChaseBossAttack()

**Comment by Kenzzer** [comment]
Yep, I just made a new version before your report, can you download it please.

**Comment by x3m77rus** [comment]
Thanks, now compiles successfully.
Also a little question: does matter order of rounds in enum? I added those rounds and compiled. All seems working but anyway just asking, I'm never used enums in code.

**Comment by Kenzzer** [comment]
Yes, don't move the special round in the enum. You can add more, if you know how to.

**Comment by MAGNAT2645** [comment]
1.0.0:
Special Rounds bug:

Please, increase length of string with Special round name in chat, because russian symbols takes more length.

P.S. Sorry for my bad english.
P.S.S. i cant increase length of string every time, when you release a new version of SF2.

**Comment by x3m77rus** [comment]
Hello! After Navmesh update plugin doesn't compile. Also is any updates planned in the near future?

**Comment by Kenzzer** [comment]
Closing this issue as we resolved all of them.
